name: "Deploy latest version"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        type: environment
        required: true
    secrets:
      #AWS_ACCESS_KEY_ID:
      #  required: true
      #AWS_SECRET_ACCESS_KEY:
      #  required: true
    
concurrency:
  group: deploy
  cancel-in-progress: false
  
permissions:
  deployments: write
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: "Connect to "
        run: "echo 'test' && echo ${{ inputs.environment }}" 
  
      